// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: grpcapp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetrecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortURL string `protobuf:"bytes,1,opt,name=shortURL,proto3" json:"shortURL,omitempty"`
}

func (x *GetrecordRequest) Reset() {
	*x = GetrecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetrecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetrecordRequest) ProtoMessage() {}

func (x *GetrecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetrecordRequest.ProtoReflect.Descriptor instead.
func (*GetrecordRequest) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{0}
}

func (x *GetrecordRequest) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

type GetrecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullURL string `protobuf:"bytes,1,opt,name=fullURL,proto3" json:"fullURL,omitempty"`
	Status  string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetrecordResponse) Reset() {
	*x = GetrecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetrecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetrecordResponse) ProtoMessage() {}

func (x *GetrecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetrecordResponse.ProtoReflect.Descriptor instead.
func (*GetrecordResponse) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{1}
}

func (x *GetrecordResponse) GetFullURL() string {
	if x != nil {
		return x.FullURL
	}
	return ""
}

func (x *GetrecordResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PostrecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullURL string `protobuf:"bytes,1,opt,name=fullURL,proto3" json:"fullURL,omitempty"`
}

func (x *PostrecordRequest) Reset() {
	*x = PostrecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostrecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostrecordRequest) ProtoMessage() {}

func (x *PostrecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostrecordRequest.ProtoReflect.Descriptor instead.
func (*PostrecordRequest) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{2}
}

func (x *PostrecordRequest) GetFullURL() string {
	if x != nil {
		return x.FullURL
	}
	return ""
}

type PostrecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortURL string `protobuf:"bytes,1,opt,name=shortURL,proto3" json:"shortURL,omitempty"`
	Status   string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PostrecordResponse) Reset() {
	*x = PostrecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostrecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostrecordResponse) ProtoMessage() {}

func (x *PostrecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostrecordResponse.ProtoReflect.Descriptor instead.
func (*PostrecordResponse) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{3}
}

func (x *PostrecordResponse) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

func (x *PostrecordResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetuserrecordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid string `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *GetuserrecordsRequest) Reset() {
	*x = GetuserrecordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetuserrecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetuserrecordsRequest) ProtoMessage() {}

func (x *GetuserrecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetuserrecordsRequest.ProtoReflect.Descriptor instead.
func (*GetuserrecordsRequest) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{4}
}

func (x *GetuserrecordsRequest) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

type GetuserrecordsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullURLs      string `protobuf:"bytes,1,opt,name=fullURLs,proto3" json:"fullURLs,omitempty"`
	NoURLs        bool   `protobuf:"varint,2,opt,name=noURLs,proto3" json:"noURLs,omitempty"`
	ArrayUserURLs string `protobuf:"bytes,3,opt,name=arrayUserURLs,proto3" json:"arrayUserURLs,omitempty"`
}

func (x *GetuserrecordsResponse) Reset() {
	*x = GetuserrecordsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetuserrecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetuserrecordsResponse) ProtoMessage() {}

func (x *GetuserrecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetuserrecordsResponse.ProtoReflect.Descriptor instead.
func (*GetuserrecordsResponse) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{5}
}

func (x *GetuserrecordsResponse) GetFullURLs() string {
	if x != nil {
		return x.FullURLs
	}
	return ""
}

func (x *GetuserrecordsResponse) GetNoURLs() bool {
	if x != nil {
		return x.NoURLs
	}
	return false
}

func (x *GetuserrecordsResponse) GetArrayUserURLs() string {
	if x != nil {
		return x.ArrayUserURLs
	}
	return ""
}

type PostShortURLtouserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid     string `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	ShortURLid string `protobuf:"bytes,2,opt,name=shortURLid,proto3" json:"shortURLid,omitempty"`
}

func (x *PostShortURLtouserRequest) Reset() {
	*x = PostShortURLtouserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostShortURLtouserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostShortURLtouserRequest) ProtoMessage() {}

func (x *PostShortURLtouserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostShortURLtouserRequest.ProtoReflect.Descriptor instead.
func (*PostShortURLtouserRequest) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{6}
}

func (x *PostShortURLtouserRequest) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *PostShortURLtouserRequest) GetShortURLid() string {
	if x != nil {
		return x.ShortURLid
	}
	return ""
}

type PostShortURLtouserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PostShortURLtouserResponse) Reset() {
	*x = PostShortURLtouserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostShortURLtouserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostShortURLtouserResponse) ProtoMessage() {}

func (x *PostShortURLtouserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostShortURLtouserResponse.ProtoReflect.Descriptor instead.
func (*PostShortURLtouserResponse) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{7}
}

type CheckPGdbConnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckPGdbConnRequest) Reset() {
	*x = CheckPGdbConnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPGdbConnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPGdbConnRequest) ProtoMessage() {}

func (x *CheckPGdbConnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPGdbConnRequest.ProtoReflect.Descriptor instead.
func (*CheckPGdbConnRequest) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{8}
}

type CheckPGdbConnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Isconnected bool `protobuf:"varint,1,opt,name=isconnected,proto3" json:"isconnected,omitempty"`
}

func (x *CheckPGdbConnResponse) Reset() {
	*x = CheckPGdbConnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPGdbConnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPGdbConnResponse) ProtoMessage() {}

func (x *CheckPGdbConnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPGdbConnResponse.ProtoReflect.Descriptor instead.
func (*CheckPGdbConnResponse) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{9}
}

func (x *CheckPGdbConnResponse) GetIsconnected() bool {
	if x != nil {
		return x.Isconnected
	}
	return false
}

var File_grpcapp_proto protoreflect.FileDescriptor

var file_grpcapp_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x22, 0x2e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x22, 0x45, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x66, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x66, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x2d, 0x0a, 0x11, 0x50, 0x6f, 0x73, 0x74, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x22, 0x48,
	0x0a, 0x12, 0x50, 0x6f, 0x73, 0x74, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x75,
	0x73, 0x65, 0x72, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x72, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x55, 0x52, 0x4c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x6e, 0x6f, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x72, 0x72, 0x61, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x61, 0x72, 0x72, 0x61, 0x79, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x22, 0x53, 0x0a,
	0x19, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x74, 0x6f, 0x75,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c,
	0x69, 0x64, 0x22, 0x1c, 0x0a, 0x1a, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55,
	0x52, 0x4c, 0x74, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x16, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x47, 0x64, 0x62, 0x43, 0x6f, 0x6e,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x39, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x50, 0x47, 0x64, 0x62, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x32, 0x96, 0x03, 0x0a, 0x07, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x42, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x19, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70,
	0x70, 0x2e, 0x47, 0x65, 0x74, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x50, 0x6f, 0x73, 0x74, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x2e, 0x50, 0x6f, 0x73, 0x74,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x1e, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a,
	0x12, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x74, 0x6f, 0x75,
	0x73, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x2e, 0x50, 0x6f,
	0x73, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x74, 0x6f, 0x75, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70,
	0x70, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x74, 0x6f,
	0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x47, 0x64, 0x62, 0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x1d, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x47, 0x64,
	0x62, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x47, 0x64, 0x62,
	0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x28, 0x5a, 0x26,
	0x75, 0x72, 0x6c, 0x73, 0x68, 0x72, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x70,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcapp_proto_rawDescOnce sync.Once
	file_grpcapp_proto_rawDescData = file_grpcapp_proto_rawDesc
)

func file_grpcapp_proto_rawDescGZIP() []byte {
	file_grpcapp_proto_rawDescOnce.Do(func() {
		file_grpcapp_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcapp_proto_rawDescData)
	})
	return file_grpcapp_proto_rawDescData
}

var file_grpcapp_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_grpcapp_proto_goTypes = []interface{}{
	(*GetrecordRequest)(nil),           // 0: grpcapp.GetrecordRequest
	(*GetrecordResponse)(nil),          // 1: grpcapp.GetrecordResponse
	(*PostrecordRequest)(nil),          // 2: grpcapp.PostrecordRequest
	(*PostrecordResponse)(nil),         // 3: grpcapp.PostrecordResponse
	(*GetuserrecordsRequest)(nil),      // 4: grpcapp.GetuserrecordsRequest
	(*GetuserrecordsResponse)(nil),     // 5: grpcapp.GetuserrecordsResponse
	(*PostShortURLtouserRequest)(nil),  // 6: grpcapp.PostShortURLtouserRequest
	(*PostShortURLtouserResponse)(nil), // 7: grpcapp.PostShortURLtouserResponse
	(*CheckPGdbConnRequest)(nil),       // 8: grpcapp.CheckPGdbConnRequest
	(*CheckPGdbConnResponse)(nil),      // 9: grpcapp.CheckPGdbConnResponse
}
var file_grpcapp_proto_depIdxs = []int32{
	0, // 0: grpcapp.Actions.Getrecord:input_type -> grpcapp.GetrecordRequest
	2, // 1: grpcapp.Actions.Postrecord:input_type -> grpcapp.PostrecordRequest
	4, // 2: grpcapp.Actions.Getuserrecords:input_type -> grpcapp.GetuserrecordsRequest
	6, // 3: grpcapp.Actions.PostShortURLtouser:input_type -> grpcapp.PostShortURLtouserRequest
	8, // 4: grpcapp.Actions.CheckPGdbConn:input_type -> grpcapp.CheckPGdbConnRequest
	1, // 5: grpcapp.Actions.Getrecord:output_type -> grpcapp.GetrecordResponse
	3, // 6: grpcapp.Actions.Postrecord:output_type -> grpcapp.PostrecordResponse
	5, // 7: grpcapp.Actions.Getuserrecords:output_type -> grpcapp.GetuserrecordsResponse
	7, // 8: grpcapp.Actions.PostShortURLtouser:output_type -> grpcapp.PostShortURLtouserResponse
	9, // 9: grpcapp.Actions.CheckPGdbConn:output_type -> grpcapp.CheckPGdbConnResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcapp_proto_init() }
func file_grpcapp_proto_init() {
	if File_grpcapp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcapp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetrecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetrecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostrecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostrecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetuserrecordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetuserrecordsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostShortURLtouserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostShortURLtouserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckPGdbConnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckPGdbConnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcapp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcapp_proto_goTypes,
		DependencyIndexes: file_grpcapp_proto_depIdxs,
		MessageInfos:      file_grpcapp_proto_msgTypes,
	}.Build()
	File_grpcapp_proto = out.File
	file_grpcapp_proto_rawDesc = nil
	file_grpcapp_proto_goTypes = nil
	file_grpcapp_proto_depIdxs = nil
}
