// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: grpcapp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetrecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortURL string `protobuf:"bytes,1,opt,name=shortURL,proto3" json:"shortURL,omitempty"`
}

func (x *GetrecordRequest) Reset() {
	*x = GetrecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetrecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetrecordRequest) ProtoMessage() {}

func (x *GetrecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetrecordRequest.ProtoReflect.Descriptor instead.
func (*GetrecordRequest) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{0}
}

func (x *GetrecordRequest) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

type GetrecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullURL string `protobuf:"bytes,1,opt,name=fullURL,proto3" json:"fullURL,omitempty"`
	Status  string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetrecordResponse) Reset() {
	*x = GetrecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetrecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetrecordResponse) ProtoMessage() {}

func (x *GetrecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetrecordResponse.ProtoReflect.Descriptor instead.
func (*GetrecordResponse) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{1}
}

func (x *GetrecordResponse) GetFullURL() string {
	if x != nil {
		return x.FullURL
	}
	return ""
}

func (x *GetrecordResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CheckPGdbConnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckPGdbConnRequest) Reset() {
	*x = CheckPGdbConnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPGdbConnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPGdbConnRequest) ProtoMessage() {}

func (x *CheckPGdbConnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPGdbConnRequest.ProtoReflect.Descriptor instead.
func (*CheckPGdbConnRequest) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{2}
}

type CheckPGdbConnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Connected bool `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
}

func (x *CheckPGdbConnResponse) Reset() {
	*x = CheckPGdbConnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPGdbConnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPGdbConnResponse) ProtoMessage() {}

func (x *CheckPGdbConnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPGdbConnResponse.ProtoReflect.Descriptor instead.
func (*CheckPGdbConnResponse) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{3}
}

func (x *CheckPGdbConnResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

var File_grpcapp_proto protoreflect.FileDescriptor

var file_grpcapp_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x22, 0x2e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x22, 0x45, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x66, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x66, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x16, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x47, 0x64, 0x62, 0x43, 0x6f, 0x6e, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x50, 0x47, 0x64, 0x62, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x32, 0x9d,
	0x01, 0x0a, 0x07, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x42, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70,
	0x70, 0x2e, 0x47, 0x65, 0x74, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x2e, 0x47, 0x65, 0x74,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e,
	0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x47, 0x64, 0x62, 0x43, 0x6f, 0x6e, 0x6e, 0x12,
	0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50,
	0x47, 0x64, 0x62, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x47,
	0x64, 0x62, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f,
	0x5a, 0x1d, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x72, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x2f, 0x63, 0x6d,
	0x64, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcapp_proto_rawDescOnce sync.Once
	file_grpcapp_proto_rawDescData = file_grpcapp_proto_rawDesc
)

func file_grpcapp_proto_rawDescGZIP() []byte {
	file_grpcapp_proto_rawDescOnce.Do(func() {
		file_grpcapp_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcapp_proto_rawDescData)
	})
	return file_grpcapp_proto_rawDescData
}

var file_grpcapp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpcapp_proto_goTypes = []interface{}{
	(*GetrecordRequest)(nil),      // 0: grpcapp.GetrecordRequest
	(*GetrecordResponse)(nil),     // 1: grpcapp.GetrecordResponse
	(*CheckPGdbConnRequest)(nil),  // 2: grpcapp.CheckPGdbConnRequest
	(*CheckPGdbConnResponse)(nil), // 3: grpcapp.CheckPGdbConnResponse
}
var file_grpcapp_proto_depIdxs = []int32{
	0, // 0: grpcapp.Actions.Getrecord:input_type -> grpcapp.GetrecordRequest
	2, // 1: grpcapp.Actions.CheckPGdbConn:input_type -> grpcapp.CheckPGdbConnRequest
	1, // 2: grpcapp.Actions.Getrecord:output_type -> grpcapp.GetrecordResponse
	3, // 3: grpcapp.Actions.CheckPGdbConn:output_type -> grpcapp.CheckPGdbConnResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcapp_proto_init() }
func file_grpcapp_proto_init() {
	if File_grpcapp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcapp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetrecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetrecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckPGdbConnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckPGdbConnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcapp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcapp_proto_goTypes,
		DependencyIndexes: file_grpcapp_proto_depIdxs,
		MessageInfos:      file_grpcapp_proto_msgTypes,
	}.Build()
	File_grpcapp_proto = out.File
	file_grpcapp_proto_rawDesc = nil
	file_grpcapp_proto_goTypes = nil
	file_grpcapp_proto_depIdxs = nil
}
