// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: grpcapp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetrecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortURL string `protobuf:"bytes,1,opt,name=ShortURL,proto3" json:"ShortURL,omitempty"`
}

func (x *GetrecordRequest) Reset() {
	*x = GetrecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetrecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetrecordRequest) ProtoMessage() {}

func (x *GetrecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetrecordRequest.ProtoReflect.Descriptor instead.
func (*GetrecordRequest) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{0}
}

func (x *GetrecordRequest) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

type GetrecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullURL string `protobuf:"bytes,1,opt,name=FullURL,proto3" json:"FullURL,omitempty"`
	Status  string `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *GetrecordResponse) Reset() {
	*x = GetrecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetrecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetrecordResponse) ProtoMessage() {}

func (x *GetrecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetrecordResponse.ProtoReflect.Descriptor instead.
func (*GetrecordResponse) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{1}
}

func (x *GetrecordResponse) GetFullURL() string {
	if x != nil {
		return x.FullURL
	}
	return ""
}

func (x *GetrecordResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PostrecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullURL string `protobuf:"bytes,1,opt,name=FullURL,proto3" json:"FullURL,omitempty"`
}

func (x *PostrecordRequest) Reset() {
	*x = PostrecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostrecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostrecordRequest) ProtoMessage() {}

func (x *PostrecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostrecordRequest.ProtoReflect.Descriptor instead.
func (*PostrecordRequest) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{2}
}

func (x *PostrecordRequest) GetFullURL() string {
	if x != nil {
		return x.FullURL
	}
	return ""
}

type PostrecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortURL string `protobuf:"bytes,1,opt,name=ShortURL,proto3" json:"ShortURL,omitempty"`
	Status   string `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *PostrecordResponse) Reset() {
	*x = PostrecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostrecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostrecordResponse) ProtoMessage() {}

func (x *PostrecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostrecordResponse.ProtoReflect.Descriptor instead.
func (*PostrecordResponse) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{3}
}

func (x *PostrecordResponse) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

func (x *PostrecordResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetuserrecordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid string `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *GetuserrecordsRequest) Reset() {
	*x = GetuserrecordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetuserrecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetuserrecordsRequest) ProtoMessage() {}

func (x *GetuserrecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetuserrecordsRequest.ProtoReflect.Descriptor instead.
func (*GetuserrecordsRequest) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{4}
}

func (x *GetuserrecordsRequest) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

type GetuserrecordsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullURLs      string   `protobuf:"bytes,1,opt,name=FullURLs,proto3" json:"FullURLs,omitempty"`
	NoURLs        bool     `protobuf:"varint,2,opt,name=NoURLs,proto3" json:"NoURLs,omitempty"`
	ArrayUserURLs []string `protobuf:"bytes,3,rep,name=ArrayUserURLs,proto3" json:"ArrayUserURLs,omitempty"`
}

func (x *GetuserrecordsResponse) Reset() {
	*x = GetuserrecordsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetuserrecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetuserrecordsResponse) ProtoMessage() {}

func (x *GetuserrecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetuserrecordsResponse.ProtoReflect.Descriptor instead.
func (*GetuserrecordsResponse) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{5}
}

func (x *GetuserrecordsResponse) GetFullURLs() string {
	if x != nil {
		return x.FullURLs
	}
	return ""
}

func (x *GetuserrecordsResponse) GetNoURLs() bool {
	if x != nil {
		return x.NoURLs
	}
	return false
}

func (x *GetuserrecordsResponse) GetArrayUserURLs() []string {
	if x != nil {
		return x.ArrayUserURLs
	}
	return nil
}

type PostShortURLtouserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid     string `protobuf:"bytes,1,opt,name=Userid,proto3" json:"Userid,omitempty"`
	ShortURLid string `protobuf:"bytes,2,opt,name=ShortURLid,proto3" json:"ShortURLid,omitempty"`
}

func (x *PostShortURLtouserRequest) Reset() {
	*x = PostShortURLtouserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostShortURLtouserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostShortURLtouserRequest) ProtoMessage() {}

func (x *PostShortURLtouserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostShortURLtouserRequest.ProtoReflect.Descriptor instead.
func (*PostShortURLtouserRequest) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{6}
}

func (x *PostShortURLtouserRequest) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *PostShortURLtouserRequest) GetShortURLid() string {
	if x != nil {
		return x.ShortURLid
	}
	return ""
}

type PostShortURLtouserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PostShortURLtouserResponse) Reset() {
	*x = PostShortURLtouserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapp_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostShortURLtouserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostShortURLtouserResponse) ProtoMessage() {}

func (x *PostShortURLtouserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapp_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostShortURLtouserResponse.ProtoReflect.Descriptor instead.
func (*PostShortURLtouserResponse) Descriptor() ([]byte, []int) {
	return file_grpcapp_proto_rawDescGZIP(), []int{7}
}

var File_grpcapp_proto protoreflect.FileDescriptor

var file_grpcapp_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x22, 0x45, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x46,
	0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x46, 0x75,
	0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2d, 0x0a,
	0x11, 0x50, 0x6f, 0x73, 0x74, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x46, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x22, 0x48, 0x0a, 0x12,
	0x50, 0x6f, 0x73, 0x74, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x75, 0x73, 0x65,
	0x72, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x72, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x75, 0x73,
	0x65, 0x72, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x4e, 0x6f, 0x55, 0x52, 0x4c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x4e,
	0x6f, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x41, 0x72, 0x72, 0x61, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x22, 0x53, 0x0a, 0x19, 0x50,
	0x6f, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x74, 0x6f, 0x75, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x69, 0x64,
	0x22, 0x1c, 0x0a, 0x1a, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c,
	0x74, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xb6,
	0x02, 0x0a, 0x07, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3e, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x50, 0x6f,
	0x73, 0x74, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x6f, 0x73, 0x74, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x75, 0x73, 0x65, 0x72, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x12,
	0x50, 0x6f, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x74, 0x6f, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x74, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x73,
	0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x74, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x20, 0x5a, 0x1e, 0x75, 0x72, 0x6c, 0x73, 0x68,
	0x72, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_grpcapp_proto_rawDescOnce sync.Once
	file_grpcapp_proto_rawDescData = file_grpcapp_proto_rawDesc
)

func file_grpcapp_proto_rawDescGZIP() []byte {
	file_grpcapp_proto_rawDescOnce.Do(func() {
		file_grpcapp_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcapp_proto_rawDescData)
	})
	return file_grpcapp_proto_rawDescData
}

var file_grpcapp_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_grpcapp_proto_goTypes = []interface{}{
	(*GetrecordRequest)(nil),           // 0: proto.GetrecordRequest
	(*GetrecordResponse)(nil),          // 1: proto.GetrecordResponse
	(*PostrecordRequest)(nil),          // 2: proto.PostrecordRequest
	(*PostrecordResponse)(nil),         // 3: proto.PostrecordResponse
	(*GetuserrecordsRequest)(nil),      // 4: proto.GetuserrecordsRequest
	(*GetuserrecordsResponse)(nil),     // 5: proto.GetuserrecordsResponse
	(*PostShortURLtouserRequest)(nil),  // 6: proto.PostShortURLtouserRequest
	(*PostShortURLtouserResponse)(nil), // 7: proto.PostShortURLtouserResponse
}
var file_grpcapp_proto_depIdxs = []int32{
	0, // 0: proto.Actions.Getrecord:input_type -> proto.GetrecordRequest
	2, // 1: proto.Actions.Postrecord:input_type -> proto.PostrecordRequest
	4, // 2: proto.Actions.Getuserrecords:input_type -> proto.GetuserrecordsRequest
	6, // 3: proto.Actions.PostShortURLtouser:input_type -> proto.PostShortURLtouserRequest
	1, // 4: proto.Actions.Getrecord:output_type -> proto.GetrecordResponse
	3, // 5: proto.Actions.Postrecord:output_type -> proto.PostrecordResponse
	5, // 6: proto.Actions.Getuserrecords:output_type -> proto.GetuserrecordsResponse
	7, // 7: proto.Actions.PostShortURLtouser:output_type -> proto.PostShortURLtouserResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcapp_proto_init() }
func file_grpcapp_proto_init() {
	if File_grpcapp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcapp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetrecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetrecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostrecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostrecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetuserrecordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetuserrecordsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostShortURLtouserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapp_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostShortURLtouserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcapp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcapp_proto_goTypes,
		DependencyIndexes: file_grpcapp_proto_depIdxs,
		MessageInfos:      file_grpcapp_proto_msgTypes,
	}.Build()
	File_grpcapp_proto = out.File
	file_grpcapp_proto_rawDesc = nil
	file_grpcapp_proto_goTypes = nil
	file_grpcapp_proto_depIdxs = nil
}
